import { ethers, network } from "hardhat";
import * as fs from "node:fs";
import * as path from "node:path";

// Known MultiVault addresses. On chainId 31337 we deploy a MockMultiVault.
const MULTIVAULT_INTUITION = "0x6E35cF57A41fA15eA0EaE9C33e751b01A784Fe7e";
const MULTIVAULT_TESTNET = "0x2Ece8D4dEdcB9918A398528f3fa4688b1d2CAB91";

const DEFAULT_VERSION_LABEL = process.env.INITIAL_VERSION || "v2.0.0";

async function main() {
  const [deployer] = await ethers.getSigners();
  const { chainId } = await ethers.provider.getNetwork();
  const balance = await ethers.provider.getBalance(deployer.address);

  console.log("─".repeat(60));
  console.log(`Network:     ${network.name} (chainId ${chainId})`);
  console.log(`Deployer:    ${deployer.address}`);
  console.log(`Balance:     ${ethers.formatEther(balance)} ETH/TRUST`);
  console.log("─".repeat(60));

  // ── 1. Resolve or deploy MultiVault ──────────────────────────────
  let multiVault: string;
  if (chainId === 31337n) {
    console.log("\n① Deploying MockMultiVault (local network)…");
    const Mock = await ethers.getContractFactory("MockMultiVault");
    const mock = await Mock.deploy();
    await mock.waitForDeployment();
    multiVault = await mock.getAddress();
    console.log(`   MockMultiVault → ${multiVault}`);
  } else if (chainId === 13579n) {
    multiVault = MULTIVAULT_TESTNET;
    console.log(`\n① Using Intuition Testnet MultiVault: ${multiVault}`);
  } else if (chainId === 1155n) {
    multiVault = MULTIVAULT_INTUITION;
    console.log(`\n① Using Intuition Mainnet MultiVault: ${multiVault}`);
  } else {
    throw new Error(
      `Unsupported chainId ${chainId}. Supported: 31337 (local), 13579 (testnet), 1155 (mainnet).`,
    );
  }

  // ── 2. Deploy V2 logic implementation ────────────────────────────
  console.log("\n② Deploying IntuitionFeeProxyV2 (logic impl)…");
  const V2Factory = await ethers.getContractFactory("IntuitionFeeProxyV2");
  const v2Impl = await V2Factory.deploy();
  await v2Impl.waitForDeployment();
  const v2Addr = await v2Impl.getAddress();
  console.log(`   IntuitionFeeProxyV2 → ${v2Addr}`);

  // ── 3. Deploy Factory implementation (UUPS) ──────────────────────
  console.log("\n③ Deploying IntuitionFeeProxyFactory implementation…");
  const FactoryFactory = await ethers.getContractFactory("IntuitionFeeProxyFactory");
  const factoryImpl = await FactoryFactory.deploy();
  await factoryImpl.waitForDeployment();
  const factoryImplAddr = await factoryImpl.getAddress();
  console.log(`   Factory impl        → ${factoryImplAddr}`);

  // ── 4. Deploy ERC1967 proxy for Factory + initialize ─────────────
  console.log("\n④ Deploying ERC1967Proxy for the Factory + initialize…");
  const initialVersion = ethers.encodeBytes32String(DEFAULT_VERSION_LABEL);
  const initData = factoryImpl.interface.encodeFunctionData("initialize", [
    v2Addr,
    initialVersion,
    deployer.address, // factory owner — swap to Safe for mainnet
  ]);

  const ERC1967ProxyFactory = await ethers.getContractFactory("ERC1967Proxy");
  const factoryProxy = await ERC1967ProxyFactory.deploy(factoryImplAddr, initData);
  await factoryProxy.waitForDeployment();
  const factoryAddr = await factoryProxy.getAddress();
  console.log(`   Factory (proxy)     → ${factoryAddr}  ← use this in the webapp`);

  // ── 5. Write to webapp .env.local ────────────────────────────────
  const envPath = path.resolve(__dirname, "../../webapp/.env.local");
  const envBlock = [
    `# Generated by packages/contracts/scripts/deploy.ts on chainId ${chainId}`,
    `# (overwrite freely — safe to commit as .env.example only)`,
    `VITE_FACTORY_ADDRESS=${factoryAddr}`,
    `VITE_IMPLEMENTATION_ADDRESS=${v2Addr}`,
    "",
  ].join("\n");

  let finalEnv = envBlock;
  if (fs.existsSync(envPath)) {
    // Preserve other keys (e.g. VITE_WALLETCONNECT_PROJECT_ID)
    const existing = fs.readFileSync(envPath, "utf-8");
    const filtered = existing
      .split("\n")
      .filter(
        (line) =>
          !line.startsWith("VITE_FACTORY_ADDRESS=") &&
          !line.startsWith("VITE_IMPLEMENTATION_ADDRESS=") &&
          !line.startsWith("# Generated by packages/contracts/scripts/deploy.ts"),
      )
      .join("\n")
      .trim();
    finalEnv = (filtered ? filtered + "\n\n" : "") + envBlock;
  }
  fs.writeFileSync(envPath, finalEnv);
  console.log(`\n⑤ Updated ${envPath}`);

  // ── Summary ──────────────────────────────────────────────────────
  console.log("\n" + "═".repeat(60));
  console.log(" DEPLOYMENT SUMMARY");
  console.log("═".repeat(60));
  console.log(` MultiVault       ${multiVault}`);
  console.log(` V2 logic impl    ${v2Addr}`);
  console.log(` Factory impl     ${factoryImplAddr}`);
  console.log(` Factory (proxy)  ${factoryAddr}`);
  console.log(` Initial version  ${DEFAULT_VERSION_LABEL} (${initialVersion})`);
  console.log("═".repeat(60));

  if (chainId === 31337n) {
    console.log("\nNext steps:");
    console.log("  1. Keep the hardhat node running (terminal 1).");
    console.log("  2. MetaMask → Add network → RPC http://127.0.0.1:8545 · chainId 31337 · symbol ETH.");
    console.log("  3. Import one of the hardhat test private keys printed by `run node` (account #0 has 10k ETH).");
    console.log("  4. `bun webapp:dev` (terminal 3) → open http://localhost:3000/deploy.");
  } else {
    console.log("\nNext steps:");
    console.log("  1. `bun webapp:dev` — the webapp will pick up the new addresses via .env.local.");
    console.log("  2. Connect the appropriate wallet (deployer/admin).");
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("\nDeployment failed:\n", error);
    process.exit(1);
  });
